### ISSUE TITLE
Generated Monologue --> Facebook profile pic?

### ISSUE THREAD

**Issue by wannabeCitizen** [QuantifiedSelfless/gulper#21]
Need a way to choose who is the person that was Amelia's ex on a given night because we'll need to print  a picture of that person and make sure Mandy has the ability to look at their facebook profile quickly.

This could be a thing the processor does -- make sure it is able to get one photo of the person as well as offer up the profile info.

Thoughts on how to accomplish this?

**Comment by mynameisfiber** [comment]
Maybe what we want to do is have a processor that just returns `True`/`False` and then on check in, if they are `True` also print out their picture.  We'd need a printer at checkin, but we would also be save in printing a picture of someone we _knew_ was there.

**Comment by mynameisfiber** [comment]
I'm closing since it seems this has been done in #19
