### ISSUE TITLE
Variable Requests (No User, POST)

### ISSUE THREAD

**Issue by wannabeCitizen** [QuantifiedSelfless/gulper#27]
The RecommenderProcessor does not care about what user is playing, so it may not need to send a userid (it could, if needed). It also needs to send a list of strings to the process handler, which may be better achieved with a POST. Thoughts?

**Comment by mynameisfiber** [comment]
i added an attribute to the processor that can be turned toggled to toggle requiring a user:

```
class OpenProcessor(BaseProcessor):
    auth = False
```

Also, right now the handlers are called with either GET or POST (thanks to @mbarrenecheajr) so the processor can do whatever it wants.  Personally, I think using `request.get_arguments` is versatile, but if you really want to read from the post body it's available at `request.body`
