### ISSUE TITLE
Amelia's Data

### ISSUE THREAD

**Issue by wannabeCitizen** [QuantifiedSelfless/gulper#9]
Need a way to have pre-set data for Amelia on both Mirror and How Ur Tracked and be sure the other actors' wristbands work for the exhibits they need

**Comment by mynameisfiber** [comment]
Just run them through the processor as usual and take note of which user id they have.  At checking we just associate their wristband with that userid as per normal.

**Comment by wannabeCitizen** [comment]
This is not a solution to this problem because we can't use real data, we have to plant very specific data related to the story/world for it to work. Also, they aren't actually signing up for any (or all) of the shows.

What I propose is that the exhibits that the actors need to play, we just make sure to set aside ID bands for them and have conditions directly in the game that grab the hard-coded data. Thoughts?

We just have to also be sure that they all have permissions for the games they need to interact with. For instance, Bo probably needs permissions for the whole data arcade, Lily for personal news, and Amelia for mirror and how ur tracked. I think that's it though.

**Comment by mynameisfiber** [comment]
This has been taken care of by creating actor user-id's using the normal ticketing procedure so they can use rfid's just like the rest of us and then manually editing their data.
